name: 'Enshan'

on:
  schedule:
    - cron: '30 */8 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      
      - name: Install Python
        run: |
          sudo apt update && \
          sudo apt install python3

      - name: requirements
        run : pip3 install -r requirements.txt

      - name: CheckIn
        env:
          cookie_enshan: ${{ secrets.cookie_enshan }}
          PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN }}
        run: |
          python3 Enshan.py
