name: V2freeCheckin

on: 
  release:
    types: [published]
  push:
    branches: 
      - master
  schedule:
    - cron: 27 7,17 * * *
  watch:
    types: [started]
   
jobs:
   Task:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id  # 自己点的 start

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Python #安装python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: requirements
      run: |
        pip3 install -r requirements.txt
    - name: Checkin #开始签到
      env: 
        ACCOUNTS: ${{ secrets.ACCOUNTS }} # accounts 提供
      run: | 
        echo `date +"%Y-%m-%d %H:%M:%S"` begin > time.log
        python checkin.py
    - name: Commit
      run: |
        git config --global user.email founder.yu@foxmail.com
        git config --global user.name founder-yu
        git add .
        git commit -m "update" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
