name: V2freeCheckin

on: 
  release:
    types: [published]
  push:
    branches: 
      - master
  schedule:
    - cron: 27 7,17 * * *
  watch:
    types: [started]
   
jobs:
   Task:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id  # 自己点的 start

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Python #安装python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: requirements
      run: |
        pip3 install -r requirements.txt
    - name: Read config from secrets  #读取机密
      env: 
        CONFIG_ID: ${{ secrets.CONFIG_ID }} # secrets_id 提供
        CONFIG_PWD: ${{ secrets.CONFIG_PWD }} # secrets_key 提供
      run: | 
        cp checkin.py checkin1.py
        echo $CONFIG_ID > configid.txt
        echo $CONFIG_PWD > configpwd.txt
        sed -i '5 r configid.txt' checkin1.py
        sed -i '7 r configpwd.txt' checkin1.py
    - name: Checkin #开始签到
      run: | 
        echo `date +"%Y-%m-%d %H:%M:%S"` begin > time.log
        python checkin1.py
    - name: Delete secrets config #删除机密
      run: | 
        rm -f checkin1.py
        rm -f configid.txt
        rm -f configpwd.txt
    - name: Commit
      run: |
        git config --global user.email founder.yu@foxmail.com
        git config --global user.name founder-yu
        git add .
        git commit -m "update" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
